package com.smartprocurement.entity;

public enum NotificationEventType {
    BOOKING_CONFIRMED,
    BOOKING_CONFIRMATION,
    SLOT_REMINDER,
    QUEUE_APPROACHING,
    START_TRAVELLING,
    QUEUE_UPDATED,
    QUEUE_CHANGED,
    CENTRE_CHANGED,
    RESCHEDULE_REQUEST,
    CANCELLATION_REQUEST,
    OWNER_APPROVAL,
    PROCUREMENT_COMPLETED,
    PAYMENT_COMPLETED
}

